### ISSUE TITLE
Nalezené problémy (SSL zabezpečení, varování)

### ISSUE THREAD

**Issue by lachtanek** [filipsedivy/PHP-EET#11]
Zdravím, narazil jsem na 2 problémy:
- CURLOPT_SSL_VERIFYPEER je nastavené na false ve vaší implementaci SoapClient (chtělo by to aspoň možnost zvenku změnit)
- není možné nijak získat varování, které vrátilo EET (odpověď->Varovani)
Pokud jde o chyby, můžu poslat PR, jinak bych rád nějaké argumenty, proč to tak je.
Kromě těchto věcí je knihovna super.
Díky

**Comment by alzbet** [comment]
K tomu druhému bodu (Varovani) - řekl bych, že to vyhozuje Dispatcher v ServerException (kód + popis). Pak je otázka, jestli k tomu přistupovat jako k EetException v příkladu. V určitých případech (technická chyba -1) určitě ano. Při chybách 5 (špatný bkp) nebo 6 (špatné DIČ) už by se na účtenku tisknul špatný BKP a PKP.

**Comment by filipsedivy** [comment]
Díky za přimpomínku 👍. V další verzi dojde k úpravám.

**Comment by filipsedivy** [comment]
Ve verzi 3.1.0, která bude vydána během následujících týdnů toto bude již opravené.
