### ISSUE TITLE
Chyba po přepnutí do produkčního prostředí

### ISSUE THREAD

**Issue by bingoplayer** [filipsedivy/PHP-EET#15]
Zdravím,
kód jsem zprovoznil v testovacím prostředí playground a napojil na eshop (vše fungovalo). Po přepnutí na produkční prostředí a překlopení na náš certifikát však hlásí kód tuto chybu:

`Fatal error: Uncaught exception 'FilipSedivy\EET\Exceptions\CertificateException' with message 'The certificate has failed to export.' in /home/web/public_html/shop/eet/EETLib/filipsedivy-PHP-EET-ea05b33/src/Certificate.php:57 Stack trace: #0 /home/web/public_html/shop/eet/vytvor-uctenku.php(13): FilipSedivy\EET\Certificate->__construct('/home/web/...', 'eet') #1 {main} thrown in /home/web/public_html/shop/eet/EETLib/filipsedivy-PHP-EET-ea05b33/src/Certificate.php on line 57`

Je prosím chyba v certifikátu nebo jsem špatně překlopil prostředí? Děkuji.

**Comment by filipsedivy** [comment]
Toto je chyba u vás

**Comment by filipsedivy** [comment]
Naučte se podávat issue, zamykám, neřeším.
