### ISSUE TITLE
Certifikat se nepodarilo vyexportovat

### ISSUE THREAD

**Issue by Musilda** [filipsedivy/PHP-EET#19]
Při vložení certifikátu, se zobrazí následující chyba:

Fatal error: Uncaught exception 'FilipSedivy\EET\Exceptions\ClientException' with message 'Certifikat se nepodarilo vyexportovat.' in /home/www/equitime.cz/www/equitime.cz/wp-content/plugins/toret-eet/includes/vendor/filipsedivy/php-eet/src/Certificate.php:31 Stack trace: #0 /home/www/equitime.cz/www/equitime.cz/wp-content/plugins/toret-eet/admin/views/admin.php(48): FilipSedivy\EET\Certificate->__construct('/home/www/equit...', 'eet') #1 /home/www/equitime.cz/www/equitime.cz/wp-content/plugins/toret-eet/admin/class-toret-eet-admin.php(145): include_once('/home/www/equit...') #2 [internal function]: Toret_Eet_Admin->display_plugin_admin_page('') #3 /home/www/equitime.cz/www/equitime.cz/wp-includes/class-wp-hook.php(298): call_user_func_array(Array, Array) #4 /home/www/equitime.cz/www/equitime.cz/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters('', Array) #5 /home/www/equitime.cz/www/equitime.cz/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #6 /home/www/equitime.cz/www/equitime.cz/wp-admin/admin.php(222) in /home/www/equitime.cz/www/equitime.cz/wp-content/plugins/toret-eet/includes/vendor/filipsedivy/php-eet/src/Certificate.php on line 31

Netušíte, co by to mohlo způsobit? Proč se certifikát nevyexportoval?

Chtěl jsem issue označit štítkem, ale nikde to tu ve formuláři nevidím.

**Comment by filipsedivy** [comment]
Certifikát nemusí jít vyexportovat z mnoha důvodů.

1/ Pokud máš testovací certifikát od daňové správy, tak musíš používat playground server, jinak jej nemůžeš používat
2/ Může být chybné heslo
3/ Jde certifikát v PC otevřít, nebo hlásí chybu? 
- Forpsi má nyní s tímto problém. Při kopírování p12 usekne posledních cca 20 bajtů a dělá to paseku po té. Nesedí po té ani CRC checksum.

Dodej výpis kde definuješ Certificate + kde nastavuješ Dispatcher. **Nazapomeň zakrýt umáznout heslo k certifikátu.**

**Comment by Musilda** [comment]
Už jsem to vyřešil, chyba byla na mé straně. Provozní certifikát si bral heslo pro testovací certifikát. 
Ještě se chci zeptat, mám tu starší verzi knihovny, kde se volal:
$dispatcher  = new Dispatcher( Playground, $certificate );
pro produkci to je
$dispatcher  = new Dispatcher( Production, $certificate ); ?

V každém případě díky za super knihovnu a hlavně za pomoc.

**Comment by filipsedivy** [comment]
Ano je to tak. Ale i přes to, doporučuji aktualizovat. Přístupnost metod se nezměnila, mnoho věcí v jádru se zrychlilo a mnoho věcí se i upravilo.

Nová verze umí instalovat i bez composeru.

**Comment by Musilda** [comment]
Včera jsem to zkoušel, ale nerozchodil jsem to hned, takže to aktualizuji později. Přispěl jsem na vývoj. Ještě jednou díky.
