### ISSUE TITLE
Sestavení zprávy pro opětovné odeslání tržby

### ISSUE THREAD

**Issue by drachouk** [filipsedivy/PHP-EET#21]
Neodojde li ke spojení se serverem MFCR a nedostalu li FIK, tak si ukládám do databáze BKP a PKP. Jak sestavím zprávu pro opětovné odeslání např. pomocí CRONu? Co by měla obsahovat?

**Comment by filipsedivy** [comment]
Nastavte hodnoty v třídě Receipt.

**Comment by swedik** [comment]
stejne udaje, akorat prvni_zaslani nastavite na FALSE

**Comment by drachouk** [comment]
Neni treba se nejak odkazat na tu prvni neuspesnou platbu? Kdyz by zakaznik chtel casem overit zda jeho uctenka s PKP byla dodatecne zaregistrovana, tak by to neslo, kdyz tam nebude vazba mezi prvnim neuspesnym a druhym uspesnym opakovanym odeslanim.

**Comment by boom1234** [comment]
Neni to treba, neuspesna platba ani nedojde na servery FU. Je nutne pouze dodrzet odeslani do 48 hodin od prijeti platby fyzicky.

**Comment by filipsedivy** [comment]
Jak bylo již řečeno, tak platby nejsou vázány na sebe a proto stačí jen nastavit [prvni_zaslani](https://github.com/filipsedivy/PHP-EET/blob/22d3d01a1e1ce206d5a12195159d957da894b1bf/src/Receipt.php#L27-L31) na ```false```.
