### ISSUE TITLE
curl hlavicky

### ISSUE THREAD

**Issue by lampaczcz** [filipsedivy/PHP-EET#22]
Zdravim,

jste si jist ze se posilaji hlavicky v curl, ktere definujete v promenne $headers?

```
$headers = array(
            'User-Agent: PHP-SOAP',
            'Content-Type: text/xml; charset=utf-8',
            'SOAPAction: "' . $action . '"',
            'Content-Length: ' . strlen($request),
        );
        $options = array(
            CURLOPT_VERBOSE        => false,
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_POST           => true,
            CURLOPT_POSTFIELDS     => $request,
            CURLOPT_HEADER         => $headers,
            CURLOPT_HTTPHEADER     => array(sprintf('Content-Type: %s', $version == 2 ? 'application/soap+xml' : 'text/xml'), sprintf('SOAPAction: %s', $action)),
            CURLOPT_SSL_VERIFYPEER => false
        );
```

> CURLOPT_HEADER - TRUE to include the header in the output.
> CURLOPT_HTTPHEADER - An array of HTTP header fields to set, in the format array('Content-type: text/plain', 'Content-length: 100')

Vy sice nastavite hlavicky do promenne headers, ale http hlavicky posilate pouze content-type + soapaction

**Comment by filipsedivy** [comment]
Díky za připomínku 👍. V další verzi bude opraveno.

**Comment by filipsedivy** [comment]
Do připravované verze 3.1.0 je toto opraveno + možnost modifikovat již stávající nastavení curl a možnost přidat nové parametry curl
