### ISSUE TITLE
Chyba - Instalace bez composeru pomocí souboru

### ISSUE THREAD

**Issue by jprkna** [filipsedivy/PHP-EET#24]
Zdravím, 

zkoušel jsem nainstalovat závislosti bez composeru dle návodu a pomocí souboru install_without_composer.php
Když nahraji soubor na web a spustím, hodí to chybu HTTP error 500.
error.log vypíše násleující:

[15-Sep-2017 09:05:23 Europe/Prague] PHP Parse error:  syntax error, unexpected '[' in /hosting/www/eet/install_without_composer.php on line 190

Děkuji.

**Comment by filipsedivy** [comment]
Jedná se nejspíš o starší verzi PHP. Udělal jsem update, kde se ověruje oproti composer.json zda je všechno, tak jak má být. Zkus to instalovat přes poslední [commit](https://raw.githubusercontent.com/filipsedivy/PHP-EET/22d3d01a1e1ce206d5a12195159d957da894b1bf/install_without_composer.php).

**Comment by jprkna** [comment]
Po updatu to píše následující hlášku, zarážející je ta první věta:

File composer.json is not exists
Your version of PHP is not compatible with this library
The minimum version is: 
Current version of PHP: 5.3.29

**Comment by filipsedivy** [comment]
Jestli myslíš ```File composer.json is not exists```. Tak bych neřekl. Protože pokud stáhneš jen soubor **install_without_composer.php** tak soubor **composer.json** neexistuje a tudíž  je nutné jej stáhnout. Ale hláška ***Current version of PHP: 5.3.29** mluví za vše. Knihovna vyžaduje minimálně PHP verzi **5.6.0**.

**Comment by jprkna** [comment]
Aktualizoval jsem PHP na verzi 5.6.0 a vše nainstalovalo. 
Díky za pomoc.
