### ISSUE TITLE
Storno

### ISSUE THREAD

**Issue by standus** [filipsedivy/PHP-EET#32]
Zdravim,
nekde jsem cetl, ze pro odeslani storno uctenky se odesle se zapornou castkou.
V dokumentaci jsem ovsem nenasel jestli jake udaje se pouziji pri odeslani. Jestli ty se kteryma se to odeslalo nebo nove udaje?

Diky

**Comment by filipsedivy** [comment]
Ahoj,

storno se odesílá se zápornou částkou a **není** vázán na předchozí platbu. To znamená, že se odešle jen záporná částka se zcela novými údaji
