### ISSUE TITLE
composer verze 3.0.1 x 3.1.0

### ISSUE THREAD

**Issue by geniv** [filipsedivy/PHP-EET#34]
instaloval jsem tuto (super per prace! ;) ) komponentu a stahla se mi jako nejnovejsi verze 3.0.1, ale v readme je deklamovano ze verze pro DI je od verze 3.1.0, ale tato neexistuje v tazich, takze jsem musel instalovat jako dev-master, je to chyba? a nebo je komponenta jen v nejake meziverzi?

**Comment by filipsedivy** [comment]
Jojo, já vím 😄 . Strašně se stydím, ale furt DI rozšíření pro Nette mám v lokálním Gitu a není to zde ano jako dev-master. Přiznám se, že teď jsem moc neměl času na aktualizaci, ale rád bych to nějak dotáhl. Je tam pár změn, tak jsem to chtěl dotáhnout spolu s Nette DI. Vydrž prosím chvilku, a dám to aspoň do dev-master.

**Comment by geniv** [comment]
v pohode :) ja jen jestli o tom vis ;) a ze jsem to implementoval pres DI a DI me nadalo ze extenze chybi.

**Comment by filipsedivy** [comment]
Kdybys potřeboval to obejít, tak tady je screencast jak to obejít přes services.

https://www.youtube.com/watch?v=PqLLHGUkv_g

**Comment by geniv** [comment]
pekna prace ;) me uz to funguje, problem jsem odhlalil velice rychle ;) mam tam momentalne master a budu se tesit na 3.1.0, bych na tvou komponentu pak udelal jeste wrapper jako dalsi komponentu do sbirky abych nemusel zadavat udaje z uradu a mel tam globali kontext pro dalsi weby.

**Comment by filipsedivy** [comment]
👍 Hotovo

- https://github.com/filipsedivy/PHP-EET/releases/tag/v3.1.0
- https://github.com/filipsedivy/PHP-EET#nette-rozš%C3%ADřen%C3%AD
