### ISSUE TITLE
Vymena certifikatu

### ISSUE THREAD

**Issue by morki** [filipsedivy/PHP-EET#35]
http://www.etrzby.cz/cs/oznameni-pro-vyvojare

Bude nutne neco upravovat v projektech vyuzivajicich tuto knihovnu?

Diky moc :)

**Comment by filipsedivy** [comment]
Nebude třeba nic upravovat. Na to že dělají velké halo okolo, tak to vlastně nic není.
Nemění se klientský certifikát ale ten na serveru, tedy vlastně nic důležitého.

**Comment by Tirus91** [comment]
@filipsedivy nejsem si tak úplně jistý. Koukal jsem do kódu a nejsem si jist, zda tam máš kontrolu CA. Pokud ne, tak se nic nemění v kódu a je to jak píšeš, že se mění jen serverová část MFČR.. Ale máš tam někde zapracovanou kontrolu? Osobně bych ji tam prdnul ;) 
CURL option -> CURLOPT_SSL_VERIFYPEER, ale bude to trošku hraní si s nastavením

**Comment by filipsedivy** [comment]
V kódu kontrola CA není. Nevidím důvod proč kontrolovat CA oproti serveru. URL je natvrdo ve schématu pokud nepoužíváš vlastní. 
Pokud bys potřeboval cURL rozšířit, tak máš tam k dispozici metodu `setCurlOption($name, $value)` ve třídě `Dispatcher`

**Comment by morki** [comment]
Super diky moc za info :)
