### ISSUE TITLE
Chybná hodnota PKP

### ISSUE THREAD

**Issue by TomasHalasz** [filipsedivy/PHP-EET#39]
Zdravím, někdy od 23.12. mi začal playground i produkční prostředí vracet warning 3 - chybná hodnota PKP. Vůbec nikde nemůžu najít co přesně to znamená. Nesetkal jste se s tím už někdo ?

díky moc

**Comment by jakovec** [comment]
Expirovany certifikat?

**Comment by TomasHalasz** [comment]
Ne, tím to není. Dělá to na playgroundu s těmi testovacími certifikáty, i v ostrém prostředí s platnými certifikáty ... 
Zatím hledám v čem mám rozdíl oproti prosinci před 23.12.. Vím, že jsem aktualizoval composerem celý projekt tzn. nette a všechny další závislosti. Warning 3 se mi zatím projevuje na dvou instalacích. Jedna je na Windowsech, druhá na Ubuntu. A pak ještě vývojový stroj s OSX Catalina. Ale na žádném z nich jsem neaktualizoval nic v PHP, takže tím to nebude.

**Comment by lukasjanikcz** [comment]
@TomasHalasz Vrací warning nebo chybovou hlášku 3, tj. "XML zpráva nevyhověla kontrole XML schématu.". Tento problém řešíme my. Jelikož jsme neprováděli žádnou aktualizaci, nejspíše bude chyba na protistraně.

**Comment by lukasjanikcz** [comment]
Tak update, teď jsme to zkoušeli a požadavky nám prošly správně. Zkuste to taky a dejte info.

**Comment by TomasHalasz** [comment]
@lukasjanikcz vrací warning 3 - Chybna hodnota PKP. BKP i FIK dostanu. A zkoušel jsem to teď na playgroundu a mám to stále stejné. Na produkci také, ale předpokládám že jen s aktualizovanými komponentami. Ještě zkusím rozběhnout starší verzi jak se bude chovat.

**Comment by lukasjanikcz** [comment]
@TomasHalasz Takže během dnešního dopoledne ¨jste bez problému dostával FIK kódy?

**Comment by TomasHalasz** [comment]
@lukasjanikcz Ano, bez potíží. Dostával.

**Comment by TomasHalasz** [comment]
Vyzkoušel jsem starou verzi aplikace z listopadu 2019 a EET na playground mi tam prochází bez warningu. Zkouším to na stejném stroji a se stejnými daty. 

Konfigurace:
PHP | 7.3.5
Tracy | 2.7.2
Server Apache/2.4.39 (Unix) PHP/7.3.5

Funkční konfig:
contributte/console | v0.5
contributte/translation | 0.1.0
filipsedivy/php-eet | v4.0.1
guzzlehttp/guzzle | 6.4.1
guzzlehttp/promises | v1.3.1
guzzlehttp/psr7 | 1.6.1
h4kuna/ares | v1.4.6
h4kuna/data-type | v2.1.6
jkuchar/pdfresponse | v0.4.0
latte/latte | v2.5.3
mpdf/mpdf | v7.1.9
myclabs/deep-copy | 1.9.3
netpromotion/profiler | v1.1.2
nette/application | v3.0.2
nette/bootstrap | v3.0.1
nette/caching | v3.0.0
nette/component-model | v3.0.0
nette/database | v3.0.3
nette/di | v3.0.1
nette/finder | v2.5.1
nette/forms | v3.0.1
nette/http | v3.0.3
nette/mail | v3.1.0
nette/neon | v3.0.0
nette/php-generator | v3.2.3
nette/robot-loader | v3.2.0
nette/routing | v3.0.0
nette/security | v3.0.2
nette/schema | v1.0.1
nette/utils | v3.0.2
nittro/nette-bridges | v2.1.3
paragonie/random_compat | v9.99.99
petrknap/php-profiler | v1.3.0
petrknap/php-singleton | v1.0.0
php-mime-mail-parser/php-mime-mail-parser | 5.0.5
psr/container | 1.0.0
psr/http-message | 1.0.1
psr/log | 1.1.2
ralouphie/getallheaders | 3.0.3
ramsey/uuid | 3.8.0
robrichards/wse-php | 2.0.3
robrichards/xmlseclibs | 3.0.4
setasign/fpdi | 1.6.2
symfony/config | v4.3.8
symfony/console | v4.3.8
symfony/filesystem | v4.3.8
symfony/polyfill-ctype | v1.12.0
symfony/polyfill-mbstring | v1.12.0
symfony/polyfill-php73 | v1.12.0
symfony/service-contracts | v1.1.8
symfony/translation | v4.3.8
symfony/translation-contracts | v1.1.7
symfony/validator | v4.3.8
tracy/tracy | v2.7.1

Nefunkční konfig:

contributte/console | v0.5
-- | --
contributte/translation | 0.1.0
filipsedivy/php-eet | v4.0.1
guzzlehttp/guzzle | 6.5.2
guzzlehttp/promises | v1.3.1
guzzlehttp/psr7 | 1.6.1
h4kuna/ares | v1.4.6
h4kuna/data-type | v2.1.6
halasz/trynx-support-form | v1.0.4
jkuchar/pdfresponse | v0.4.0
latte/latte | v2.5.4
mpdf/mpdf | v7.1.9
myclabs/deep-copy | 1.9.4
netpromotion/profiler | v1.1.2
nette/application | v3.0.2
nette/bootstrap | v3.0.1
nette/caching | v3.0.1
nette/component-model | v3.0.0
nette/database | v3.0.5
nette/di | v3.0.2
nette/finder | v2.5.1
nette/forms | v3.0.2
nette/http | v3.0.3
nette/mail | v3.1.0
nette/neon | v3.1.0
nette/php-generator | v3.3.1
nette/robot-loader | v3.2.1
nette/routing | v3.0.0
nette/security | v3.0.2
nette/schema | v1.0.1
nette/utils | v3.0.3
nittro/nette-bridges | v2.1.3
paragonie/random_compat | v9.99.99
petrknap/php-profiler | v1.3.0
petrknap/php-singleton | v1.0.0
php-mime-mail-parser/php-mime-mail-parser | 5.0.5
psr/container | 1.0.0
psr/http-message | 1.0.1
psr/log | 1.1.2
ralouphie/getallheaders | 3.0.3
ramsey/uuid | 3.8.0
robrichards/wse-php | 2.0.3
robrichards/xmlseclibs | 3.0.4
setasign/fpdi | 1.6.2
symfony/config | v4.4.2
symfony/console | v4.4.2
symfony/filesystem | v5.0.2
symfony/polyfill-ctype | v1.13.1
symfony/polyfill-mbstring | v1.13.1
symfony/polyfill-php73 | v1.13.1
symfony/service-contracts | v2.0.1
symfony/translation | v4.4.2
symfony/translation-contracts | v2.0.1
symfony/validator | v4.4.2
tracy/tracy | v2.7.2
unio/pohoda-export | dev-master #0be6

**Comment by filipsedivy** [comment]
Zdravím,

zkoušel jsem to, a mělo by být vše v pořádku. 

Jediné v čem byla chyba je, že pokud zkoušíte playground tak bylo nutné si stáhnout aktuální certifikáty z etržby. Ty co jsou v repositáři jsou finančním úřadem zneplatněné. 

Zasílám i kus testovacího kódu:

```php
<?php

require_once __DIR__ . '/vendor/autoload.php';

use FilipSedivy\EET;
use Ramsey\Uuid\Uuid;

$certificate = new EET\Certificate(
    __DIR__ . '/vendor/filipsedivy/php-eet/tests/Data/EET_CA1_Playground-CZ00000019.p12',
    'eet'
);

$dispatcher = new EET\Dispatcher($certificate, EET\Dispatcher::PLAYGROUND_SERVICE);

$receipt = new EET\Receipt();
$receipt->uuid_zpravy = Uuid::uuid4()->toString();
$receipt->id_provoz = '11';
$receipt->id_pokl = 'IP105';
$receipt->dic_popl = 'CZ00000019';
$receipt->porad_cis = '1';
$receipt->dat_trzby = new \DateTime();
$receipt->celk_trzba = 500;

$dispatcher->send($receipt);

var_dump('FIK: ' . $dispatcher->getFik());
var_dump('PKP: ' . $dispatcher->getPkp());
```

```json
{
    "require": {
        "filipsedivy/php-eet": "^4.0"
    }
}
```

**Comment by TomasHalasz** [comment]
Děkuji za kód, mám to v podstatě úplně stejně, jen posílám navíc DPH. 
Certifikát mám správný. Problém je v tom, že ačkoliv dostanu FIK i PKP tak se mi vrací warning 3 - chybná hodnota PKP.
Chápu to tak, že server EET zkontroloval odeslanou tržbu proti vygenerovanému PKP a nevyšel mu stejný řetězec PKP. Proto vrací warning jako propustnou chybu 3 - chybná hodnota PKP. 

PKP, který dostanu ve starší verzi a odeslání projde bez warningu je:
uGmInRoBSDcLpBhpFh9B+lOYpEgzEEIhllHmOS9O9ToX90NCx+p6fZzd5v4aTFwwEGcFA+cXweAcPjMHuCgL1qur+rkpSluWL4iBtc0shFGeE+6Wyta2S+dieETEYfbPqj6Cg7XqVV1J4TWOlPb1jGEtgIEn2+p4+HZ7OTrpnVShViBeVRcnQIXxxs19UcUAAYXEwRZNjp11lisuf8QUUP4h++O3zTmDd3XjsTJokkTiKuk39ip7S5kfvcV7XoQhNgUlnvpfCelPelHjd4qqvzv7IJSxp0AOJ71akIMo1hLPDAD1gRhxgjTm3RXnpUmr8xLyOiv0m8vHvvWGATDncA== 

PKP, který dostanu v aktuální verzi a také projde, ale s warningem 3 je:
kxK9zNsFaJqvR4WrWlz89bvfBDNhoe0LuwSz3pvhBkSPXDRnmuKQhmRFqceiGpURyNiisFZkGO2nJvrkJTz2xKOnkeMpmGJHvU5ZdruaPsHyoNHQPT2l03/TJIayXBcjAuz6+06ybkh+Cb8NRMvYJIWw09o9IVuI6/doJYMfYi39MeCS5Z4J9PyK4xGWjMHu7HLRpyBFYfZMXplG2ogkL2eFbPJpY1ffrgmOVsKDheXrs7V8u4V+3BxW+j7MwSMRKAQHt2le8NnwN9lAlw1kbElK3dJuDb8/QSZ6v5B2g6bbNbET/8qhHJcjuy203XK1REmYlT2HfflNoQ+MV2sUxA== 

Doklad, který jsem posílal je naprosto shodný. Posílám toto:
    $r->uuid_zpravy     = Uuid::uuid4()->toString();
    $r->id_provoz       = $dataForSign['eet_id_provoz'];
    $r->id_pokl         = $dataForSign['eet_id_poklad'];
    $r->dic_popl        = $dataForSign['dic_popl'];
    $r->porad_cis       = $dataToSend['porad_cis'];
    $r->dat_trzby       = $dataToSend['dat_trzby'];
    $r->celk_trzba      = $dataToSend['celk_trzba'];
    $r->prvni_zaslani   = false;
    $r->rezim = 0;
    $r->zakl_nepodl_dph = $dataToSend['zakl_nepodl_dph'];
    $r->zakl_dan1 = $dataToSend['zakl_dan1'];
    $r->dan1 = $dataToSend['dan1'];
    $r->zakl_dan2 = $dataToSend['zakl_dan2'];
    $r->dan2 = $dataToSend['dan2'];
    $r->zakl_dan3 = $dataToSend['zakl_dan3'];
    $r->dan3 = $dataToSend['dan3'];

Kde $dataToSend je:

uuid_zpravy => "84a52fbe-9511-4633-8033-be9a84f58bbd"
dic_popl => "CZ00000019"
id_provoz => "11"
id_pokl => "1"
porad_cis => "VF1192820"
dat_trzby => 
   date => "2020-01-02 19:34:50.000000"
   timezone_type => 3
   timezone => "Europe/Prague"
celk_trzba => 121.0
zakl_nepodl_dph => 0.0
zakl_dan1 => 100.0
dan1 => 21.0
zakl_dan2 => 0.0
dan2 => 0.0
zakl_dan3 => 0.0
dan3 => 0.0

Pak je tedy nějaký problém ve vygenerování PKP, protože není pro naprosto stejný doklad shodné ve staré funkční a nové verzi nette nebo některých komponent.

**Comment by TomasHalasz** [comment]
Už jsem na to přišel.
V Dispatcher.php je ve funkci getCheckCodes v aktuální verzi PHP-EET toto:
            $arr = [
                $receipt->dic_popl,
                $receipt->id_provoz,
                $receipt->id_pokl,
                $receipt->porad_cis,
                $receipt->dat_trzby->format('c'),
                $receipt->celk_trzba
            ];

Ve starší funkční je:
            $arr = [
                $receipt->dic_popl,
                $receipt->id_provoz,
                $receipt->id_pokl,
                $receipt->porad_cis,
                $receipt->dat_trzby->format('c'),
                Format::price($receipt->celk_trzba)
            ];
Doplnil jsem tedy Format::price a už to prochází bez varování :-)

**Comment by filipsedivy** [comment]
Nemáte starší verzi, jelikož toto jsem přesunul právě do automatického sestavování 

https://github.com/filipsedivy/PHP-EET/blob/1a9c4d626c3f76486aa2d82e7c34efd57ee98512/src/FilipSedivy/EET/Receipt.php#L144-L149

**Comment by TomasHalasz** [comment]
Verzi mám správnou. Příčina je podle mě v tomto:
https://github.com/filipsedivy/PHP-EET/blob/1a9c4d626c3f76486aa2d82e7c34efd57ee98512/src/FilipSedivy/EET/Dispatcher.php#L193-L197

Kde jsou Data => $receipt->buildBody() správně formátovány, ale pak je 
KontrolniKody => $this->getCheckCodes($receipt) a v $receipt jsou původní hodnoty bez formátování.

**Comment by filipsedivy** [comment]
Je to pravda. V kontrolním kódu neprobíhá formátování ceny. Toto ještě budu muset opravit.

**Comment by filipsedivy** [comment]
👍🏻 Opraveno 

4f3ae088d847aebc1936bb52993f05b32d25615c
