### ISSUE TITLE
Výpadek serveru EET nebo připojení

### ISSUE THREAD

**Issue by JardaPazdy** [filipsedivy/PHP-EET#4]
Dobrý den,
bylo by skvělé přidat řešení výpadku serveru EET nebo jinak spojení mezi zařízením a finanční správou. V tom případě by mělo být vráceno BKIP číslo, které se tiskne na účtenku místo FIK. Bylo by super, pokud by v configu šlo nastavit, po kolika vteřinách se považuje FIK za nepřijatý (myslím, že finanční správa udává 2 sec).

Děkuji

**Comment by Keberdle** [comment]
Zdravím, 
můžete prosím "aktualizovat" composer. Vrací stále verzi 2.0 bez posledních změn.
Díky

**Comment by filipsedivy** [comment]
@Keberdle Composer vrací kód z Gitu z větve master.

**Comment by Keberdle** [comment]
@filipsedivy diky za nakopnutí composer moc často nepřemlouvám.

**Comment by filipsedivy** [comment]
@Keberdle Pro příště jen, vytvoři si nové Issues, přeci jen, zde se řeší něco jiného, a akorát tu bude bordel.

**Comment by filipsedivy** [comment]
Opraveno ve verzi v3.0.0 #9 
- https://github.com/filipsedivy/PHP-EET/wiki/Z%C3%ADskán%C3%AD-BKP,-PKP-a-FIK-kódu
