### ISSUE TITLE
Storno zaslané účtenky

### ISSUE THREAD

**Issue by JardaPazdy** [filipsedivy/PHP-EET#5]
Dobrý den,
bylo by skvělé přidat funkci pro zasílání storna dříve zaslané účtenky.

Moc děkuji.

**Comment by filipsedivy** [comment]
Storno se neplánuje, neboť se jedná o knihovnu. Storno se podává podáním záporné částky.

## Storno a opravy (§ 7 ZoET)

> Vrací-li se evidovaná tržba nebo provádí-li se opravy tržby, která již byla odeslána do systému správce daně, postupuje se obdobně jako v případě evidování tržby s tím rozdílem, že tato **zadaná částka bude záporná** (mínusová položka). Postup se vztahuje na případy vrácení zboží bez uvedení důvodu, při vyřízení reklamace, u omylem zaevidované tržby nebo na případy, kdy byly údaje o evidované tržbě zaslány správci daně před přijetím tržby a zákazník nakonec zboží nezaplatil (nejčastěji půjde o zasílání zboží webovými obchody na dobírku a následné nepřevzetí zboží). Provedené storno není z technického hlediska vázáno na původně zaslanou datovou zprávu (resp. vydanou účtenku).

Více informací naleznete na [etržby.cz](http://www.etrzby.cz/cs/zpusoby-evidence-a-uctenka)
