### ISSUE TITLE
HELP: Jak vygenerovat certifikát pro testovací EET server?

### ISSUE THREAD

**Issue by rsvitak** [filipsedivy/php-eet#53]
Toto není chybový report, spíš jen obecná žádost o pomoc s EET PLAYGROUND serverem. 
Na serveru "e-trzby" jsem pro zákazníka vygeneroval certifikát, který mi funguje jen pro PRODUCTION EET server.
Zároveň jsem udělal testy s certifikáty, které jsou součástí tohoto projektu. Ty fungují pro PLAYGROUND EET server.
Mně by zajímalo jak vygenervoat certifikát pro zákazníka pro PLAYGROUND server, abych mohl spustit testování? Kromě volání na support linku EET jsem zkoušel hledat všude. Předem děkuji za jakékoliv nasměrování.

**Comment by rsvitak** [comment]
Aha, tak jsem se v dokumentaci k EET dočetl, že pro testování musí všichni používat jen předvygenerované certifikáty, viz napr. https://www.etrzby.cz/assets/cs/prilohy/EET_CA1_Playground_v1.zip

 Snad jsem to pochopil správně. Zavírám tiket...

**Comment by filipsedivy** [comment]
Pro playground generuje pouze GFŘ/MFČR. Není možné jej takto svépomoci vygenerovat.

Pokud chceš otestovat platby pomocí služby production, doporučuji použít metodu [`Dispatcher::check(Receipt $receipt): bool`](https://github.com/filipsedivy/php-eet/blob/master/src/Dispatcher.php#L86-L95). Nicméně metoda nevrací fiskální kód, ale jen bool zda je vše v pořádku. 
Tržba není na produkčním serveru zaregistrována.

**Comment by rsvitak** [comment]
Děkuju moc za odpověd. Metodu check vyzkouším.
