### ISSUE TITLE
podpora php 8.1

### ISSUE THREAD

**Issue by ZdenekKrcal** [filipsedivy/PHP-EET#59]
přešel jsem na php 8.1

ale hází mě knihovna problém:

[FilipSedivy\EET\SoapClient::doRequestByCurl](editor://open/?file=%2Fdisk_1%2Fwww%2Fcom%2Fokg-family%2Fwww%2Fvendor%2Ffilipsedivy%2Fphp-eet%2Fsrc%2FSoapClient.php&line=100&search=&replace=)(): Argument #5 ($one_way) must be of type int, bool given

**Comment by filipsedivy** [comment]
Vzhledem k tomu že EET je plánováno ukončit vládou, tak vývoj nyní dál pokračovat nebude.

Doporučuji si vytvořit fork této knihovny a svépomocí přidat podporu pro PHP 8.x.
